In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
import numpy as np
# from scipy.stats import mode
import matplotlib.pyplot as plt
import scipy.stats

# Load data

In [2]:
iris = datasets.load_iris()
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
X = iris.data[50:,[1,2]]
y = iris.target[50:]

# Majority vote classifier

In [10]:
numit = 100
model_acc = np.empty((numit,4))
ensemble_acc = np.empty(numit)

for c in range(numit):
    
    # Create an array with four models
    clfs = [
        Pipeline([ ('sc',StandardScaler()), 
                   ('clf',LogisticRegression()) 
                 ]), 
        
        Pipeline([ ('sc',StandardScaler()), 
                   ('clf',SVC()) 
                 ]),

        DecisionTreeClassifier(), 

        Pipeline([ ('sc',StandardScaler()), 
                   ('clf',KNeighborsClassifier()) 
                 ])
    ]
    
    # Test/train split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    # Train and test the four models
    y_pred = np.empty( (len(clfs),len(y_test)) , int)
    for i, model in enumerate(clfs):  
        model.fit(X_train,y_train)
        y_pred[i,:] = model.predict(X_test)
        model_acc[c,i] = accuracy_score(y_test,y_pred[i,:])
        
    # Majority vote
    y_pred_ens = scipy.stats.mode(y_pred).mode[0]
    ensemble_acc[c] = accuracy_score(y_test,y_pred_ens)

(array([0.9335, 0.922 , 0.8835, 0.9195]), 0.9215000000000001)

In [11]:
np.mean(model_acc,axis=0), np.mean(ensemble_acc)

(array([0.9335, 0.922 , 0.8835, 0.9195]), 0.9215000000000001)